import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import logo from "@/public/logo-2.png";
import Image from "next/image";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}>
        <header className="sticky top-0 z-50 backdrop-blur bg-black border-b border-(--border)">
          <div className="max-w-5xl mx-auto px-4 flex items-center justify-between">
            <h1 className="text-2xl font-semibold tracking-tight">Allergy Guide</h1>
            <div className="flex items-center gap-3">
              {/* <span className="inline-flex h-2 w-2 rounded-full bg-(--accent) shadow-[0_0_12px_rgba(220,38,38,0.8)]"></span> */}
              <Image src={logo} alt="STK Logo" className="w-20 h-20" />
            </div>
          </div>
          <div className="h-1 bg-(--accent)/80"></div>
        </header>
        <div className="max-w-5xl mx-auto px-4 py-8">
          {children}
        </div>
      </body>
    </html>
  );
}
